In [1]:
import torch
from torch import nn

In [5]:
class Model(nn.Module): # nn.Module is a base class who provides us all the functionalities require to build a neural network
    def __init__(self, num_features) -> None:
        super().__init__()
        self.linear = nn.Linear(in_features = num_features, out_features = 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):
        out = self.linear(features)
        out = self.sigmoid(out)

        return out

In [6]:
# Create a dummy dataset
features = torch.rand(10, 5)

# Model Object
model = Model(features.shape[1])

# Forward pass
model(features) # PyTorch Recommendation - They used magic method call() so that you directly call the object

tensor([[0.4318],
        [0.5803],
        [0.5552],
        [0.5255],
        [0.5589],
        [0.5218],
        [0.5715],
        [0.5706],
        [0.5005],
        [0.5541]], grad_fn=<SigmoidBackward0>)

In [7]:
model.linear.weight

Parameter containing:
tensor([[-0.3228, -0.0238,  0.4340, -0.3447,  0.4361]], requires_grad=True)

In [8]:
model.linear.bias

Parameter containing:
tensor([0.1397], requires_grad=True)

In [9]:
!pip install torchinfo

In [10]:
from torchinfo import summary
summary(model, input_size = features.shape)

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [13]:
class Model(nn.Module): # nn.Module is a base class who provides us all the functionalities require to build a neural network
    def __init__(self, num_features) -> None:
        super().__init__()
        self.linear1 = nn.Linear(in_features = num_features, out_features = 3) # Hidden layer 1
        self.relu = nn.ReLU()

        self.linear2 = nn.Linear(in_features = 3, out_features = 1) # Hidden layer 2
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):
        out = self.linear1(features)
        out = self.relu(out)
        out = self.linear2(out)
        out = self.sigmoid(out)

        return out

In [14]:
# Create a dummy dataset
features = torch.rand(10, 5)

# Model Object
model = Model(features.shape[1])

# Forward pass
model(features) # PyTorch Recommendation - They used magic method call() so that you directly call the object

tensor([[0.6363],
        [0.6155],
        [0.6366],
        [0.6249],
        [0.6352],
        [0.6111],
        [0.6219],
        [0.6194],
        [0.6269],
        [0.6177]], grad_fn=<SigmoidBackward0>)

In [15]:
summary(model, input_size = features.shape)

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [16]:
class Model(nn.Module): # nn.Module is a base class who provides us all the functionalities require to build a neural network
    def __init__(self, num_features) -> None:
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(in_features = num_features, out_features = 3), # Hidden layer 1
            nn.ReLU(),

            nn.Linear(in_features = 3, out_features = 1), # Hidden layer 2
            nn.Sigmoid()
        )

    def forward(self, features):
        out = self.network(features)
        return out

In [17]:
# Create a dummy dataset
features = torch.rand(10, 5)

# Model Object
model = Model(features.shape[1])

# Forward pass
model(features) # PyTorch Recommendation - They used magic method call() so that you directly call the object

tensor([[0.6145],
        [0.6110],
        [0.6145],
        [0.6145],
        [0.6145],
        [0.6029],
        [0.6145],
        [0.6145],
        [0.6145],
        [0.6145]], grad_fn=<SigmoidBackward0>)

In [18]:
summary(model, input_size = features.shape)

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [ ]:
class MyANN(nn.Module):
    def __init__(self, input_shape) -> None:
        super().__init__()

        # Building NN
        network = nn.Sequential(
            nn.Linear(in_features=input_shape[1], out_features=2),
            nn.ReLU(),
            nn.Linear(in_features=2, out_features=1),
            nn.ReLU(),
            nn.Linear(in_features=2, out_features=1),
            nn.Sigmoid(),
        )

    def forward(self, features):
        out = self.network(features)
        return out

In [ ]:
# Parameters
learning_rate = 0.1
epochs = 25

In [ ]:
# Defining loss functions
loss_function = nn.BCELoss()

In [ ]:
# Creating Model
model = MyANN(input_shape=features.shape)

# Define Optimizer
optimizer = torch.optim.SGD(model.parameters(), lr = learning_rate) # model.parameters() is an iterator who iterate over all the model parameters

# Define loop
for i in range(epochs):
    # Forward pass
    y_pred = model(features)

    # Calculating loss
    loss = loss_function(y_pred, y_train.view(-1, 1))

    # Clear Gradients - Recommended here to first clear the gradients and then calculate it frest
    optimizer.zero_grad()

    # backward pass
    loss.backward()

    # paramters update
    optimizer.step()

    # print loss in each epoch
    print(f'Epoch: {i + 1}, Loss: {loss.item()}')

In [ ]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')