In [1]:
import torch
print(torch.__version__)

2.6.0+cu124


In [2]:
if torch.cuda.is_available():
    print("GPU is available!")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available. Using CPU.")

GPU is available!
Using GPU: Tesla T4


## `Tensor Creation Methods`

In [3]:
# This method will assign a memory to create a tensor of provided shape and return the existing numbers at that location
a = torch.empty(2, 3)
a

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 4.2039e-45, 4.2039e-45]])

In [4]:
# Check type
type(a)

torch.Tensor

In [7]:
# Using zeros
torch.zeros(size = [2, 3], dtype = torch.float32)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [8]:
# using ones
torch.ones(size = [2, 3])

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [9]:
# using rand
torch.rand(size = [2, 3])

tensor([[0.6769, 0.4579, 0.1405],
        [0.6777, 0.8727, 0.5257]])

In [10]:
# manual_seed - for regenerating the same array
torch.manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [11]:
# using tensor
torch.tensor(
    data = [[1,2,3],[4,5,6]],
    dtype = torch.float32,
    requires_grad = False,
    pin_memory = True # The tensor will directly loded into pin-memory and not pager-memory, for faster loading
)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [12]:
# arange
print("using arange ->", torch.arange(0,10,2))

# using linspace
print("using linspace ->", torch.linspace(0,10,10))

# using eye - Identity Matrix tensor
print("using eye ->", torch.eye(5))

# using full - torch.ones(size = (m, n)) * constant( = 5)
print("using full ->", torch.full((3, 3), 5))

using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


---

## `Tensor Shape`

In [13]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [14]:
x.shape

torch.Size([2, 3])

In [ ]:
torch.empty_like(x)
# This method will copy the shape of the tensor passed as an argument

tensor([[     134842408414608,       96429401449888,     3503044046096754],
        [-2738188572259385344,  7020378893157883663,  8389754676633367105]])

In [15]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [16]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [17]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])

---

## `Tensor DataTypes`

In [18]:
# find data type
x.dtype

torch.int64

In [19]:
# assign data type
torch.tensor([1.0, 2.0, 3.0], dtype = torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [20]:
torch.tensor([1, 2, 3], dtype = torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [21]:
# using to() - Type Conversion
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


---

## `Mathematical Operations`

In [22]:
x = torch.rand(2,2)
x

tensor([[0.8694, 0.5677],
        [0.7411, 0.4294]])

In [23]:
# Scalar Operations

# addition
x + 2

# substraction
x - 2

# multiplication
x * 3

# division
x / 3

# int division
(x * 100) // 3

# mod
((x * 100) // 3) % 2

# power
x ** 2

tensor([[0.7559, 0.3223],
        [0.5492, 0.1844]])

In [24]:
# Element wise operation
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.8854, 0.5739, 0.2666],
        [0.6274, 0.2696, 0.4414]])
tensor([[0.2969, 0.8317, 0.1053],
        [0.2695, 0.3588, 0.1994]])


In [25]:
# Shape must be same

# add
a + b

# sub
a - b

# multiply
a * b

# division
a / b

# power
a ** b

# mod
a % b

tensor([[0.2916, 0.5739, 0.0560],
        [0.0885, 0.2696, 0.0426]])

In [26]:
c = torch.tensor([1, -2, 3, -4])
c

tensor([ 1, -2,  3, -4])

In [27]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [28]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [29]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])
d

tensor([1.9000, 2.3000, 3.7000, 4.4000])

In [30]:
# round
torch.round(d)

tensor([2., 2., 4., 4.])

In [31]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [32]:
# floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [34]:
# clamp - Clipping in a certing range
torch.clamp(d, min = 2, max = 3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

In [35]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[7., 9., 2.],
        [0., 5., 9.]])

In [36]:
# Reduction operation

# sum
torch.sum(e)

# sum along columns
torch.sum(e, dim = 0) # same as `axis` parameter in numpy

# sum along rows
torch.sum(e, dim = 1)

tensor([18., 14.])

In [37]:
# mean
torch.mean(e)

# mean along col
torch.mean(e, dim=0)

tensor([3.5000, 7.0000, 5.5000])

In [38]:
# median
torch.median(e)

tensor(5.)

In [39]:
# max and min
torch.max(e)
torch.min(e)

tensor(0.)

In [40]:
# product
torch.prod(e)

tensor(0.)

In [41]:
# standard deviation
torch.std(e)

tensor(3.7238)

In [42]:
# variance
torch.var(e)

tensor(13.8667)

In [43]:
# argmax
torch.argmax(e)

tensor(1)

In [44]:
# argmin
torch.argmin(e)

tensor(3)

---

## `Matrix operations`

In [45]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[3, 4, 9],
        [6, 2, 0]])
tensor([[6, 2],
        [7, 9],
        [7, 3]])


In [46]:
# matrix multiplcation - dot product
torch.matmul(f, g)

tensor([[109,  69],
        [ 50,  30]])

In [47]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

# dot product - only works with 1D Tensors
torch.dot(vector1, vector2)

tensor(11)

In [48]:
# transpose
torch.transpose(f, 0, 1)

tensor([[3, 6],
        [4, 2],
        [9, 0]])

In [50]:
torch.transpose(f, dim0 = 1, dim1 = 0)

tensor([[3, 6],
        [4, 2],
        [9, 0]])

In [52]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[3., 4., 3.],
        [7., 0., 9.],
        [0., 9., 6.]])

In [53]:
# determinant
torch.det(h)

tensor(-222.)

In [54]:
# inverse
torch.inverse(h)

tensor([[ 0.3649, -0.0135, -0.1622],
        [ 0.1892, -0.0811,  0.0270],
        [-0.2838,  0.1216,  0.1261]])

---

## `Comparison operations`

In [55]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[9, 5, 4],
        [8, 8, 6]])
tensor([[0, 0, 0],
        [0, 1, 3]])


In [56]:
# Element wise comparison - Shape must be same

# greater than
i > j

# less than
i < j

# equal to
i == j

# not equal to
i != j

tensor([[True, True, True],
        [True, True, True]])

---

## `Special functions`

In [57]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[0., 1., 1.],
        [7., 9., 4.]])

In [59]:
# log - base e
torch.log(input = k)

tensor([[  -inf, 0.0000, 0.0000],
        [1.9459, 2.1972, 1.3863]])

In [60]:
# exp
torch.exp(k)

tensor([[1.0000e+00, 2.7183e+00, 2.7183e+00],
        [1.0966e+03, 8.1031e+03, 5.4598e+01]])

In [61]:
# sqrt
torch.sqrt(k)

tensor([[0.0000, 1.0000, 1.0000],
        [2.6458, 3.0000, 2.0000]])

In [62]:
# sigmoid
torch.sigmoid(k)

tensor([[0.5000, 0.7311, 0.7311],
        [0.9991, 0.9999, 0.9820]])

In [67]:
# softmax
torch.softmax(k, dim = 1)

tensor([[0.1554, 0.4223, 0.4223],
        [0.1185, 0.8756, 0.0059]])

In [68]:
# relu
torch.relu(k)

tensor([[0., 1., 1.],
        [7., 9., 4.]])

---

## `Inplace Operations`

In [69]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.0874, 0.0041, 0.1088],
        [0.1637, 0.7025, 0.6790]])
tensor([[0.9155, 0.2418, 0.1591],
        [0.7653, 0.2979, 0.8035]])


In [70]:
# _ methods
m.add_(n)

tensor([[1.0028, 0.2458, 0.2680],
        [0.9289, 1.0004, 1.4825]])

In [71]:
m # Updated

tensor([[1.0028, 0.2458, 0.2680],
        [0.9289, 1.0004, 1.4825]])

In [72]:
n

tensor([[0.9155, 0.2418, 0.1591],
        [0.7653, 0.2979, 0.8035]])

In [73]:
torch.relu(m)

tensor([[1.0028, 0.2458, 0.2680],
        [0.9289, 1.0004, 1.4825]])

In [74]:
m.relu_()

tensor([[1.0028, 0.2458, 0.2680],
        [0.9289, 1.0004, 1.4825]])

In [75]:
m

tensor([[1.0028, 0.2458, 0.2680],
        [0.9289, 1.0004, 1.4825]])

---

## `Copying a Tensor`

In [76]:
b = a.clone()

In [77]:
a

tensor([[0.8854, 0.5739, 0.2666],
        [0.6274, 0.2696, 0.4414]])

In [78]:
b

tensor([[0.8854, 0.5739, 0.2666],
        [0.6274, 0.2696, 0.4414]])

In [79]:
a[0][0] = 10

In [80]:
a

tensor([[10.0000,  0.5739,  0.2666],
        [ 0.6274,  0.2696,  0.4414]])

In [81]:
b

tensor([[0.8854, 0.5739, 0.2666],
        [0.6274, 0.2696, 0.4414]])

In [82]:
id(a)

137381764742320

In [83]:
id(b)

137381765177296