In [29]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [30]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [31]:
df.shape

(569, 33)

In [32]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [33]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

### train test split

In [34]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

### scaling

In [35]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [36]:
X_train

array([[-0.50982318, -1.40827946, -0.48951731, ..., -0.45622304,
         0.95496791,  0.51933876],
       [-0.95075155,  1.37424725, -0.95118524, ..., -0.77174877,
         0.85606382, -0.10827569],
       [ 0.20596961, -1.2473454 ,  0.30870528, ..., -0.01116408,
        -0.10330587,  0.50040706],
       ...,
       [-0.71024517, -1.10507035, -0.70179281, ..., -0.57252604,
         0.08461191,  0.48434381],
       [ 4.04834535, -0.20010776,  4.0737803 , ...,  0.73803645,
        -2.04677126, -1.6124851 ],
       [ 2.7312866 ,  1.15267136,  2.68085268, ...,  1.49800577,
        -0.48903182, -0.342914  ]])

In [37]:
y_train

130    B
248    B
421    B
83     M
0      M
      ..
457    B
352    M
478    B
212    M
339    M
Name: diagnosis, Length: 455, dtype: object

### Label Encoding

In [38]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [39]:
y_train

array([0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0,

In [40]:
# Converting numpy array to torch dataframe
X_train = torch.from_numpy(X_train).to(torch.float32)
y_train = torch.from_numpy(y_train).to(torch.float32)
X_test = torch.from_numpy(X_test).to(torch.float32)
y_test = torch.from_numpy(y_test).to(torch.float32)

In [65]:
class MyANN():
    def __init__(self, learning_rate, epochs) -> None:
      self._weights = torch.rand(size = [X_train.shape[1], 1], dtype = torch.float32, requires_grad = True)
      self._intercept = torch.tensor(data = 0.0, dtype = torch.float32, requires_grad = True)
      self._epochs = epochs
      self._learning_rate = learning_rate

    def fit(self, X_train, y_train):
        for i in range(self._epochs):
            y_pred = torch.sigmoid(torch.matmul(X_train, self._weights) + self._intercept)
            loss = torch.nn.functional.binary_cross_entropy(input = y_pred, target = y_train)
            loss.backward()
            # Update weights and bias within torch.no_grad() block
            with torch.no_grad():
                print(self._weights.grad)
                self._weights -= self._learning_rate * self._weights.grad
                self._intercept -= self._learning_rate * self._intercept.grad

                # Zero gradients after updating parameters
                self._weights.grad.zero_()
                self._intercept.grad.zero_()

    def predict():
        pass

In [66]:
obj = MyANN(learning_rate=0.001, epochs=1)
obj.fit(X_train, y_train.reshape(-1, 1))

tensor([[-0.0840],
        [-0.0467],
        [-0.0770],
        [-0.0748],
        [ 0.0873],
        [ 0.0741],
        [ 0.0239],
        [-0.0085],
        [ 0.0853],
        [ 0.1652],
        [-0.0230],
        [ 0.0620],
        [-0.0106],
        [-0.0333],
        [ 0.1435],
        [ 0.1370],
        [ 0.0946],
        [ 0.0862],
        [ 0.0973],
        [ 0.1557],
        [-0.0838],
        [-0.0575],
        [-0.0756],
        [-0.0720],
        [ 0.0533],
        [ 0.0389],
        [ 0.0186],
        [-0.0183],
        [ 0.0087],
        [ 0.0982]])


In [60]:
obj._weights

tensor([[0.2642],
        [0.6072],
        [0.4017],
        [0.6822],
        [0.6701],
        [0.4457],
        [0.8625],
        [0.5878],
        [0.0647],
        [0.5103],
        [0.8744],
        [0.2004],
        [0.7196],
        [0.0761],
        [0.4245],
        [0.6825],
        [0.2193],
        [0.1894],
        [0.6028],
        [0.5797],
        [0.0543],
        [0.8582],
        [0.5888],
        [0.3740],
        [0.4572],
        [0.7786],
        [0.7032],
        [0.3772],
        [0.3591],
        [0.6468]], requires_grad=True)

In [19]:
X_train.shape

torch.Size([455, 30])

In [20]:
y_train.shape

torch.Size([455])

### Numpy arrays to PyTorch tensors

In [ ]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [ ]:
X_train_tensor.shape

torch.Size([455, 30])

In [ ]:
y_train_tensor.shape

torch.Size([455])

### Defining the model

In [ ]:
class MySimpleNN():

  def __init__(self, X):

    self.weights = torch.rand(X.shape[1], 1, dtype=torch.float64, requires_grad=True)
    self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

  def forward(self, X):
    z = torch.matmul(X, self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self, y_pred, y):
    # Clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

    # Calculate loss
    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss





### Important Parameters

In [ ]:
learning_rate = 0.1
epochs = 25

### Training Pipeline

In [ ]:
# create model
model = MySimpleNN(X_train_tensor)

# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model.forward(X_train_tensor)

  # loss calculate
  loss = model.loss_function(y_pred, y_train_tensor)

  # backward pass
  loss.backward()

  # parameters update
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  # zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 3.8734547280441722
Epoch: 2, Loss: 3.747472466032905
Epoch: 3, Loss: 3.6134186400812918
Epoch: 4, Loss: 3.470439804709892
Epoch: 5, Loss: 3.322739972220773
Epoch: 6, Loss: 3.1694648115531123
Epoch: 7, Loss: 3.0100440752635733
Epoch: 8, Loss: 2.844157902489334
Epoch: 9, Loss: 2.674609873272524
Epoch: 10, Loss: 2.4944661028022916
Epoch: 11, Loss: 2.310878252311848
Epoch: 12, Loss: 2.1262855749988945
Epoch: 13, Loss: 1.9355652547438864
Epoch: 14, Loss: 1.7455326544884913
Epoch: 15, Loss: 1.5644006244127746
Epoch: 16, Loss: 1.3939717578405724
Epoch: 17, Loss: 1.240793872530291
Epoch: 18, Loss: 1.1079115183532575
Epoch: 19, Loss: 0.9976743132283318
Epoch: 20, Loss: 0.9111688924041779
Epoch: 21, Loss: 0.8476079601805322
Epoch: 22, Loss: 0.8040883970545488
Epoch: 23, Loss: 0.776156415200584
Epoch: 24, Loss: 0.759000203855423
Epoch: 25, Loss: 0.7485464460500285


In [ ]:
model.bias

tensor([-0.0940], dtype=torch.float64, requires_grad=True)

### Evaluation

In [ ]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')


Accuracy: 0.6378886103630066
