In [2]:
import torch
print(torch.__version__)

2.6.0+cu124


In [3]:
!pip install --upgrade torch

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 821.2/821.2 MB 457.7 kB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 393.1/393.1 MB 2.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.9/8.9 MB 128.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.7/23.7 MB 89.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 897.7/897.7 kB 41.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 571.0/571.0 MB 1.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 200.2/200.2 MB 5.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 52.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 22.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 158.2/158.2 MB 7.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 216.6/216.6 MB 5.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 156.8/156.8 MB 7.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2

In [3]:
torch.cuda.is_available()

True

In [4]:
torch.cuda.get_device_name(0)

'Tesla T4'

In [7]:
# Creating a Tensor
a = torch.empty(2, 3, 4) # Allocate a memory of shape provided and return the already present values at that location
a

tensor([[[0.0000e+00, 0.0000e+00, 7.8865e-30, 0.0000e+00],
         [2.8026e-45, 2.1019e-44, 2.8026e-45, 2.2421e-44],
         [2.8026e-44, 0.0000e+00, 2.0319e-43, 0.0000e+00]],

        [[7.8870e-30, 0.0000e+00, 3.3021e+37, 4.4107e-41],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [1.5835e-42, 0.0000e+00, 1.7355e-41, 0.0000e+00]]])

In [8]:
# Check type
type(a)

torch.Tensor

In [9]:
# using zeros
torch.zeros(2,3,4)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [10]:
torch.ones(2, 3, 4)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [11]:
torch.rand(2, 3, 4)# range 0-1

tensor([[[0.4265, 0.4283, 0.8429, 0.3030],
         [0.2562, 0.2662, 0.7568, 0.9184],
         [0.5798, 0.2435, 0.0511, 0.3069]],

        [[0.8554, 0.8361, 0.3422, 0.1509],
         [0.4413, 0.0793, 0.1883, 0.2650],
         [0.6453, 0.9825, 0.0328, 0.5300]]])

In [14]:
# use of seed
torch.manual_seed(42)
torch.rand(3, 4)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

In [15]:
torch.tensor(
    [1, 2, 3]
) # Your customized pytorch tensor

tensor([1, 2, 3])

In [16]:
# torch shape
a.shape

torch.Size([2, 3, 4])

In [17]:
torch.empty_like(a)

tensor([[[3.3022e+37, 4.4107e-41, 7.9990e-30, 0.0000e+00],
         [7.4466e-30, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 7.9990e-30, 0.0000e+00]],

        [[8.1420e-31, 0.0000e+00, 1.5422e+27, 4.4106e-41],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]]])

In [18]:
torch.ones_like(a)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [20]:
torch.rand_like(a)

tensor([[[0.5779, 0.9040, 0.5547, 0.3423],
         [0.6343, 0.3644, 0.7104, 0.9464],
         [0.7890, 0.2814, 0.7886, 0.5895]],

        [[0.7539, 0.1952, 0.0050, 0.3068],
         [0.1165, 0.9103, 0.6440, 0.7071],
         [0.6581, 0.4913, 0.8913, 0.1447]]])

In [21]:
temp = torch.tensor(
    [1, 2, 3]
)
torch.rand_like(temp)

RuntimeError: "check_uniform_bounds" not implemented for 'Long'

In [22]:
# Find the datatype
temp.dtype

torch.int64

In [24]:
# Tensor with datatype
torch.tensor([1,2,3], dtype = torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [25]:
temp.to(dtype = torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [27]:
# Mathematical Operations
torch.abs(temp)

tensor([1, 2, 3])

In [28]:
torch.neg(temp)

tensor([-1, -2, -3])

In [29]:
torch.round(temp)

tensor([1, 2, 3])

In [30]:
torch.ceil(torch.tensor([3.53432, 7.3534, 8.928434, 5.934]))

tensor([4., 8., 9., 6.])

In [31]:
torch.floor(torch.tensor([3.53432, 7.3534, 8.928434, 5.934]))

tensor([3., 7., 8., 5.])

In [32]:
# clamping
torch.clamp(torch.tensor([3.53432, 7.3534, 8.928434, 5.934]), max = 2, min = 3)

tensor([2., 2., 2., 2.])

In [33]:
# Reduction operations
torch.sum(temp)

tensor(6)

In [35]:
torch.sum(
    torch.tensor([
        [1,2,3],
        [4,5,6]
    ]),
    dim = 1
)

tensor([ 6, 15])

In [36]:
torch.sum(
    torch.tensor([
        [1,2,3],
        [4,5,6]
    ]),
    dim = 0
)

tensor([5, 7, 9])

In [38]:
torch.mean(
    torch.tensor([
        [1,2,3],
        [4,5,6]
    ], dtype = torch.float32),
    dim = 1
)

tensor([2., 5.])

## AutoGrad

In [8]:
import torch
tmp = torch.tensor(data = 2.0, requires_grad = True)

In [9]:
y = tmp ** 2

In [10]:
y

tensor(4., grad_fn=<PowBackward0>)

In [11]:
y.backward()

In [12]:
tmp.grad

tensor(4.)

In [19]:
# Nested Functions
a = torch.tensor(data = 2.0, requires_grad = True)
b = a ** 2
c = torch.sin(b)

In [20]:
c.backward()

In [25]:
b..retain_grad

SyntaxError: invalid syntax (ipython-input-25-2466747157.py, line 1)

In [67]:
x = torch.tensor([6.7, 9.8, 3.9])
y = torch.tensor([0.0])

In [68]:
w = torch.tensor([1.0, 1.0, 1.0], requires_grad = True)
b = torch.tensor([0.0], requires_grad = True)

In [69]:
z = x.dot(w) + b
output = torch.sigmoid(input = z)

In [70]:
loss = torch.nn.functional.binary_cross_entropy_with_logits(input=z, target=y)
# Problem using custom function - By using binary_cross_entropy_with_logits, you are letting PyTorch handle the numerical stability of the sigmoid and log operations internally. It's designed to prevent log(0) or log(1) situations that lead to NaN or inf during the backward pass, especially when y is 0 or 1.

In [71]:
loss.backward()

In [72]:
w.grad

tensor([6.7000, 9.8000, 3.9000])

In [73]:
b.grad

tensor([1.])

---